name: bbnjax
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy>=1.26
  - scipy>=1.11
  - matplotlib>=3.8
  - pandas>=2.0
  - pyyaml>=6.0
  - pip:
      - "jax[cpu]>=0.4.30"
      - equinox>=0.11.4
      - optax>=0.2.2
      - pytest>=8.0
      # - linx
      # - tinygp
      # - blackjax
      # - cobaya
